version: '3.8'

services:
  commit-checker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python312-commit-checker
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 
